"""
SkillRouter Environment for verl-agent.

Each episode:
1. Model receives a question
2. Model generates <plan> + <route> tags (assistant turn)
3. Environment parses routes, simulates sub-agent execution, returns <obs> (tool turn)
4. Model generates <verify> + optionally <final_answer> or repair <plan>
5. Repeat until <final_answer> or max_steps

Reward: correctness(final_answer, gold) - lambda * token_cost
"""

import re
import concurrent.futures
from typing import Any, Dict, List, Tuple
from copy import deepcopy

import gym
import numpy as np
from omegaconf import DictConfig


# --- Schema v1.1 Parsers ---
PLAN_RE = re.compile(r'<plan round="(\d+)">(.*?)</plan>', re.DOTALL)
SUBTASK_RE = re.compile(r'<subtask id="(\d+)" depends_on="([^"]*)">(.*?)</subtask>', re.DOTALL)
ROUTE_RE = re.compile(
    r'<route round="(\d+)" subtask="(\d+)" model="([^"]+)" skill="([^"]+)">(.*?)</route>',
    re.DOTALL,
)
VERIFY_RE = re.compile(
    r'<verify round="(\d+)" status="(pass|repair_needed)"(?: target="([^"]*)")?>(.*?)</verify>',
    re.DOTALL,
)
FINAL_RE = re.compile(r'<final_answer>(.*?)</final_answer>', re.DOTALL)


def normalize_answer(s: str) -> str:
    """Normalize answer string for comparison."""
    import string
    s = s.lower().strip()
    # Remove articles
    for art in ("a ", "an ", "the "):
        if s.startswith(art):
            s = s[len(art):]
    # Remove punctuation
    s = s.translate(str.maketrans("", "", string.punctuation))
    # Collapse whitespace
    s = " ".join(s.split())
    return s


def check_correctness(prediction: str, gold: str) -> float:
    """Check if prediction matches gold answer. Returns 1.0 or 0.0."""
    if not prediction or not gold:
        return 0.0
    pred_norm = normalize_answer(prediction)
    gold_norm = normalize_answer(gold)
    if pred_norm == gold_norm:
        return 1.0
    # Substring match (gold in pred or pred in gold)
    if gold_norm in pred_norm or pred_norm in gold_norm:
        return 1.0
    return 0.0


def simulate_sub_agent(subtask_id: str, model: str, skill: str, query: str,
                       question: str, gold: str) -> str:
    """
    Simulate sub-agent execution. Returns an <obs> string.

    In RL training, we don't actually call external APIs.
    Instead, we return a plausible observation based on the skill type.
    The reward comes from whether the final_answer is correct.
    """
    # Simple simulation: return a generic observation
    # The model must learn to produce correct final_answer regardless
    if skill == "direct_answer":
        obs = f"Based on parametric knowledge: [response to '{query}']"
    elif skill == "web_search":
        obs = f"Search results for '{query}': [relevant information retrieved]"
    elif skill == "symbolic_math":
        obs = f"Computation result for '{query}': [calculated value]"
    elif skill == "execute_python":
        obs = f"Python execution output for '{query}': [code output]"
    elif skill == "reason":
        obs = f"Reasoning result for '{query}': [logical conclusion]"
    elif skill == "database_query":
        obs = f"Database query result for '{query}': [query results]"
    elif skill == "read_document":
        obs = f"Document content for '{query}': [extracted text]"
    elif skill == "fact_check":
        obs = f"Fact check for '{query}': [verification result]"
    elif skill == "extract_field":
        obs = f"Extracted field for '{query}': [field value]"
    else:
        obs = f"Result for '{query}': [output]"
    return obs


class SingleSkillRouterEnv:
    """Single environment instance for one (question, gold) pair."""

    def __init__(self):
        self.question = None
        self.gold = None
        self.data_source = None
        self.max_turns = 3
        self.current_round = 0
        self.total_route_tokens = 0
        self.done = False
        self.final_answer = None

    def reset(self, extras: Dict):
        self.question = extras["question"]
        self.gold = extras["ground_truth"]
        self.data_source = extras.get("data_source", "unknown")
        self.max_turns = extras.get("max_turns", 3)
        self.current_round = 0
        self.total_route_tokens = 0
        self.done = False
        self.final_answer = None

    def step(self, action: str) -> Dict:
        """
        Process model's output (action) and return environment response.

        The action is the full text generated by the model, which may contain:
        - <plan> + <route> tags -> parse and simulate execution
        - <verify> + <final_answer> -> episode ends
        - <verify status="repair_needed"> + <plan> -> continue
        - <final_answer> directly -> lazy mode, episode ends
        """
        self.current_round += 1
        observations = []
        reward = 0.0
        metadata = {}

        # Check for final_answer (lazy mode or after verify pass)
        final_match = FINAL_RE.search(action)
        if final_match:
            self.final_answer = final_match.group(1).strip()
            self.done = True
            reward = check_correctness(self.final_answer, self.gold)
            metadata["correctness"] = reward
            metadata["final_answer"] = self.final_answer
            return {
                "observations": observations,
                "reward": reward,
                "done": True,
                "metadata": metadata,
            }

        # Parse routes and simulate execution
        routes = ROUTE_RE.findall(action)
        if routes:
            obs_parts = []
            for round_n, subtask_id, model, skill, query in routes:
                # Estimate token cost (rough: len of query + len of obs)
                self.total_route_tokens += len(query.split()) * 2
                obs_text = simulate_sub_agent(subtask_id, model, skill, query,
                                              self.question, self.gold)
                obs_parts.append(f'<obs subtask="{subtask_id}">{obs_text}</obs>')
            observations = [{"content": "\n".join(obs_parts)}]

        # Check if max turns exceeded
        if self.current_round >= self.max_turns:
            self.done = True
            reward = 0.0  # No final_answer produced
            metadata["timeout"] = True

        metadata["round"] = self.current_round
        metadata["n_routes"] = len(routes)

        return {
            "observations": observations,
            "reward": reward,
            "done": self.done,
            "metadata": metadata,
        }


class SkillRouterMultiProcessEnv(gym.Env):
    """
    Vectorized SkillRouter environment.
    Compatible with verl-agent's env interface.
    """

    def __init__(
        self,
        seed: int = 0,
        env_num: int = 1,
        group_n: int = 1,
        is_train: bool = True,
        env_config: DictConfig | None = None,
    ):
        super().__init__()
        self.env_num = env_num
        self.group_n = group_n
        self.batch_size = env_num * group_n
        self.is_train = is_train
        self.max_steps = env_config.max_steps if env_config else 3
        self.lambda_cost = env_config.get("lambda_cost", 0.001) if env_config else 0.001

        self.envs = [SingleSkillRouterEnv() for _ in range(self.batch_size)]
        self._executor = concurrent.futures.ThreadPoolExecutor(
            max_workers=min(self.batch_size, 64)
        )

    def reset(self, kwargs: List[Dict]) -> Tuple[List[str], List[Dict]]:
        """Reset all environments with (question, gold) pairs."""
        if len(kwargs) > self.batch_size:
            self.batch_size = len(kwargs)
            self.envs = [SingleSkillRouterEnv() for _ in range(self.batch_size)]

        obs_list = []
        info_list = []
        for i, kw in enumerate(kwargs):
            extras = {
                "question": kw["question"],
                "ground_truth": kw["ground_truth"],
                "data_source": kw.get("data_source", "unknown"),
                "max_turns": self.max_steps,
            }
            self.envs[i].reset(extras)
            obs_list.append(kw["question"])
            info_list.append({"data_source": kw.get("data_source", "unknown")})

        return obs_list, info_list

    def step(self, actions: List[str]) -> Tuple[List[str], np.ndarray, np.ndarray, List[Dict]]:
        """Step all environments with model actions."""
        results = list(self._executor.map(
            lambda args: args[0].step(args[1]),
            zip(self.envs, actions)
        ))

        next_obs = []
        rewards = np.zeros(len(actions), dtype=np.float32)
        dones = np.zeros(len(actions), dtype=bool)
        infos = []

        for i, result in enumerate(results):
            obs_content = ""
            if result["observations"]:
                obs_content = result["observations"][0]["content"]
            next_obs.append(obs_content)

            # Reward: correctness - lambda * token_cost
            correctness = result["reward"]
            token_cost = self.envs[i].total_route_tokens / 1000.0  # normalize
            rewards[i] = correctness - self.lambda_cost * token_cost

            dones[i] = result["done"]
            info = result.get("metadata", {})
            info["data_source"] = self.envs[i].data_source
            info["won"] = bool(correctness >= 1.0)
            infos.append(info)

        return next_obs, rewards, dones, infos

    def close(self):
        self._executor.shutdown(wait=False)
