set -x

ENGINE=${1:-vllm}
TRAIN_DATA="${TRAIN_DATA:-/data/xieht/verl-agent/data/skillrouter/train.parquet}"
VAL_DATA="${VAL_DATA:-/data/xieht/verl-agent/data/skillrouter/val.parquet}"
MODEL_PATH="${MODEL_PATH:-/data/xieht/LlamaFactory/outputs/router_qwen25_7b_sft}"

group_size=8                
max_turns=5                 
alpha_init=0.1              
train_batch_size=64
ppo_mini_batch_size=32
ppo_micro_batch_size=2
max_prompt_length=4096
max_response_length=2048
max_start_length=2048
max_obs_length=512
total_training_steps=200

export VLLM_ATTENTION_BACKEND=FLASH_ATTN
export HYDRA_FULL_ERROR=1
export SKILLROUTER_SYSTEM_PROMPT=/data/xieht/multiagentRL/data/sft/hf_release/system_prompt.txt
export REMOTE_API_BASE="${REMOTE_API_BASE:-https://open.xiaojingai.com/v1/}"
export REMOTE_API_KEY="${REMOTE_API_KEY:-sk-wFh8h2dhytX3J7ywOZld4IVWoEoBr8hZ8DonD60UYHDZSrYT}"
export PYTHONPATH="/data/xieht/Router-R1:/data/xieht/verl-agent:${PYTHONPATH}"

PY=/data/conda/envs/verl/bin/python

cd /data/xieht/Router-R1 && $PY /data/xieht/multiagentRL/scripts/rl/launch_grpo.py \
    algorithm.adv_estimator=grpo \
    data.train_files="['$TRAIN_DATA']" \
    data.val_files="['$VAL_DATA']" \
    data.train_data_num=null \
    data.val_data_num=null \
    data.train_batch_size=$train_batch_size \
    data.val_batch_size=100 \
    data.max_prompt_length=$max_prompt_length \
    data.max_response_length=$max_response_length \
    data.max_start_length=$max_start_length \
    data.max_obs_length=$max_obs_length \
    data.return_raw_chat=True \
    data.shuffle_train_dataloader=True \
    actor_rollout_ref.model.path="$MODEL_PATH" \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.1 \
    actor_rollout_ref.actor.optim.weight_decay=0.01 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=$ppo_mini_batch_size \
    actor_rollout_ref.actor.ppo_micro_batch_size=$ppo_micro_batch_size \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.actor.grad_clip=1.0 \
    actor_rollout_ref.actor.state_masking=true \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.name=$ENGINE \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.temperature=1.0 \
    actor_rollout_ref.rollout.top_p=1.0 \
    actor_rollout_ref.rollout.top_k=-1 \
    actor_rollout_ref.rollout.n=$group_size \
    actor_rollout_ref.rollout.n_agent=1 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.ref.log_prob_micro_batch_size=8 \
    algorithm.kl_ctrl.kl_coef=0.001 \
    algorithm.gamma=0.95 \
    algorithm.no_think_rl=false \
    ++do_route=True \
    ++api_base="$REMOTE_API_BASE" \
    ++api_key="$REMOTE_API_KEY" \
    ++cost_coe=$alpha_init \
    ++max_turns=$max_turns \
    ++reward_metric=f1 \
    trainer.logger='["console","wandb"]' \
    trainer.project_name='skillrouter-rl' \
    trainer.experiment_name="grpo_qwen25_7b_sft_4gpu" \
    trainer.n_gpus_per_node=4 \
    trainer.nnodes=1 \
    trainer.save_freq=50 \
    trainer.test_freq=50 \
    trainer.total_epochs=3 \
    trainer.total_training_steps=$total_training_steps \
    +trainer.val_before_train=True \
    trainer.default_local_dir="/data/xieht/sft/checkpoints/rl_grpo_v1" \
    "$@"
